### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by MisterZeus** [barrbrain/daala-demo#2]
barrbrain: Nice demo!

My requests would be UI-related:
- move Load Your Image above other controls
- spread controls across page, rather than on top of each other.

This way people are more likely to be able to view Daala controls AND image at the same time, without having to scroll up/down as much :-)

**Comment by barrbrain** [comment]
Good suggestions. I made the parameter controls flow horizontally.
https://github.com/barrbrain/daala-demo/commit/b3cb70e1cd1078ec0ec4fcef65ecbf3ec23f03ea
