### ISSUE TITLE
Before and After imagefile sizes in the Status text?

### ISSUE THREAD

**Issue by MisterZeus** [barrbrain/daala-demo#3]
Or I guess Original and Compressed sizes. Just to get some ballpark figures for just those 3 filters and their interactions :-)

**Comment by barrbrain** [comment]
Added a simple but pessimistic bitrate estimation with https://github.com/barrbrain/daala-demo/commit/694702ac7abd1a4514e52bac5db805f22b6fbce5
It gives NaN sometimes, and I don't know why.

**Comment by barrbrain** [comment]
Fixed the NaNs in https://github.com/barrbrain/daala-demo/commit/fb548ba988d1f473efd4b85383313a008f48206a
I wasn't handling the null vector case correctly. This also caused quantization bugs.
