### ISSUE TITLE
Large File upload displays black image

### ISSUE THREAD

**Issue by MisterZeus** [barrbrain/daala-demo#4]
I tried uploading an 8,122 KB JPEG file, it made my Firefox unresponsive for a bit (which is expected with these filesizes and processing!), BUT after a while, the output was updated and the Status read "Applied all filters in 20925 ms."

Only problem is that the output image was completely black.

MediaInfo details for input file below!

Format                                   : JPEG
File size                                : 115 MiB (probably means when decompressed out of JPEG?)
Width                                    : 10 800 pixels
Height                                   : 2 332 pixels
Display aspect ratio                     : 4.631
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 115 MiB (100%)

**Comment by barrbrain** [comment]
Handling this case would be tricky because half a gigabyte of internal buffers would be required for full-frame filters. The solution would be to halve the field width of the internal buffer and to reallocate the heap on image load.

**Comment by MisterZeus** [comment]
Alternatively, could:
- refuse massive files
- or resize them to fit within, say, a 1080p-wide canvas (or progressively subsample by 2 for speed?)
- or the halving you mentioned above!

**Comment by barrbrain** [comment]
Actually, there is a simple solution. I can limit the resolution of the canvas when rendering the image into it on the load event. I think 4K (4096 x 2160) is a reasonable upper bound, requiring an 128MB heap without changing any of the filtering code.

**Comment by barrbrain** [comment]
Applied the above strategy in https://github.com/barrbrain/daala-demo/commit/91dad0b0978a568df49f9fea12f5fd5934d531a0 and tested with http://i.imgur.com/HXSsxzn.jpg

**Comment by barrbrain** [comment]
I missed a square-root so the scaling was too aggressive. Fixed in https://github.com/barrbrain/daala-demo/commit/607bf82a35ffdf48d884951b68a0bbb4f3b41eae
