### ISSUE TITLE
Arrange demo parameters in Daala's processing order?

### ISSUE THREAD

**Issue by MisterZeus** [barrbrain/daala-demo#5]
Might they might make more sense arranged as follows?

1) lapping (maybe mention Monty's demo at https://people.xiph.org/~xiphmont/demo/daala/demo1.shtml)
2) quantisation
3) deringing

**Comment by barrbrain** [comment]
Thanks for the suggestion, there was some ambiguity in the ordering as lapping consists of a pref-filter and post-filter from the round-trip perspective.
Reordered and added a blurb about lapping in https://github.com/barrbrain/daala-demo/commit/b810c24b679e0a2ad3b2208d5f5ad5aa1df2bca9
